# Generated by Django 2.1.5 on 2019-01-18 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190113_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent', models.IntegerField(blank=True, default=0)),
                ('assented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('KR', 'Korean'), ('EN', 'English')], default='KR', max_length=2),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='response_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
