# Generated by Django 2.1.5 on 2019-02-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190118_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrelation',
            name='request_user',
        ),
        migrations.RemoveField(
            model_name='friendrelation',
            name='response_user',
        ),
        migrations.DeleteModel(
            name='FriendRelation',
        ),
    ]
