# Generated by Django 2.1.5 on 2019-02-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190113_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
