# Generated by Django 2.1.5 on 2019-01-19 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent', models.IntegerField(blank=True, default=0)),
                ('assented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_user', to=settings.AUTH_USER_MODEL)),
                ('response_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
