# Generated by Django 2.1.5 on 2019-01-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20190120_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='block',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='assent',
        ),
    ]
