# Generated by Django 2.1.5 on 2019-01-30 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20190130_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='response_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_user_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='response_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
