# Generated by Django 2.1.5 on 2019-01-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_auto_20190130_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='updated_at',
        ),
    ]
