# Generated by Django 2.1.5 on 2019-01-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(),
        ),
    ]
